### ISSUE TITLE
Plan based on the discussions at EuroBioc2019

### ISSUE THREAD

**Issue by lgatto** [statOmics/msqrob2#1]
## Overview

Anticipated functionality of the package based on the [EuroBioc2019](https://github.com/Bioconductor/EuroBioc2019/issues/3) discussion group between @statOmics @lgatto @ococrook and @cvanderaa. 

1. Read peptide-level data into a `Features` object.
```
$ x <- readFeatures(...)
$ x
A instance of class Features containing
 [1] peptides: SummarizedExperiment with 12345 rows and 8 columns 
```
2. Data pre-processing on the `Features` object as described in the BSS2019 material ([1](https://lgatto.github.io/bioc-ms-prot/bss-lab.html) and [2](https://uclouvain-cbio.github.io/BSS2019/figs/cptacAvsB_lab3_robust.html)).

3. Aggregate peptide features into protein intensities using `aggregateFeatures,Features` (to be implemented).

```
$ x <- aggregateFeatires(x, ....)
$ x
A instance of class Features containing
 [1] peptides: SummarizedExperiment with 12345 rows and 8 columns 
 [2] proteins: SummarizedExperiment with 2371 rows and 8 columns 
```

4. Apply the MSqRob analysis, which adds a new variable to the assay that is used to perform the analysis. This new variable would contain the models for each protein. Each model would be stored as a object of class `StatModel` (to be implemented).
```
x <- msqrob(x, "ProteinAccession", assay = "proteins", formula = ~ group * genotype)
``` 

5. Extract contrasts, which add a variable names `results_contrast` containing p-values, adjusted p-values, log2 fold-changes, .... to the assays rowData.

```
x <- results(x, assay = "proteins", contrast = ...)
```

## Work plan
- Update `Features` and `MsCoreUtils` (see this [PR](https://github.com/rformassspectrometry/MsCoreUtils/pull/32)) (@lgatto)
- implement the BSS2019 pre-processing on Features (@lgatto)
- Implement `StatModel` (@lgatto, @ococrook, @statOmics)
- Implement `msqrob2::msqrob` (@statOmics)
- test data: cptac spike-ins A vs B in `msqrob2` for testing, and all comparisons in `msdata`.

**Comment by cvanderaa** [comment]
I'm not sure I have the expertise required to contribute to the 4 first bullet points! But I am willing to help you providing unit tests.
