### ISSUE TITLE
bplapply issue

### ISSUE THREAD

**Issue by ococrook** [statOmics/msqrob2#13]
@statOmics 

When running the rridge regression approach I get an error, I think to do with bplapply - can you reproduce locally?
```{r,}
pe <- msqrob(object = pe, i = "protein", formula = ~-1 + condition, 
modelColumnName = "ridge", ridge = TRUE)
```
*Error in if (m == 0) { : missing value where TRUE/FALSE needed*

**Comment by statOmics** [comment]
On my local build I do not get the error and everything works fine. 
However I do get the following error message to the screen without the process to be interrupted

_Error in mcexit(0L) : ignoring SIGPIPE signal_

but at first sight this does not seem to affect the results.

**Comment by ococrook** [comment]
I'll try a clean build later and see if it is still an issue. Might be one of those "windows" things.

**Comment by ococrook** [comment]
@statOmics @lgatto 

After some digging this seems to be a biocparallel issue via bplapply.

I get the error when using `bplapply`. However the issue disappears when replacing with either `lapply` or adding `BPPARAM = serialparam()`.

This function doesn't take that long with lapply. I also do not know why this an issue on windows. I assume you are using mac @statOmics, I also have no problem on linux. 

There is also the futures package, which I generally have better experience with but do we really need parallisation?

**Comment by ococrook** [comment]
fixed
