### ISSUE TITLE
Error in Msqob

### ISSUE THREAD

**Issue by ococrook** [statOmics/msqrob2#14]
The following error in the ecoliSpikeIn.rmd. I haven't spent much time debugging

```{r,}
 pe <- msqrob(object = pe, i = "protein", formula = ~condition,  modelColumnName = "ridge", ridge = TRUE)
```
*Error in if (m == 0) { : missing value where TRUE/FALSE needed*

**Comment by ococrook** [comment]
fixed

**Comment by ekglover** [comment]
Hello, would you be able to share how you fixed this? I am having the same problem. I appreciate it was a while ago! Thanks, Emily

**Comment by lgatto** [comment]
Probably by installing the very latest version with  

```
BiocManager::install("statOmics/msqrob2")
```

but Olly will confirm.

**Comment by ekglover** [comment]
Was a problem with my data. Needed more than 1 sample per group.
