### ISSUE TITLE
warnings in hurdle method

### ISSUE THREAD

**Issue by ococrook** [statOmics/msqrob2#15]
The following warning given. If the warning is intended then we need to explain it, else we should try and remove it else people will be confused.

```{r,}
pe <- msqrobQB(object = pe, i = "proteinCount", formula = ~condition)
```
Warning in eval(family$initialize): non-integer counts in a binomial glm!

**Comment by ococrook** [comment]
Solution:

add short explination of off-set (and that this will generate a warning)

add warning = FALSE to rmd

**Comment by statOmics** [comment]
Would you include it both in the Rmd script and in the documentation of the fit function?
