### ISSUE TITLE
Update to StatModel

### ISSUE THREAD

**Issue by lgatto** [statOmics/msqrob2#18]
Hi @statOmics @ococrook - I inadvertently pushed to `statOmics/msqrob2` instead of `lgatto/msqrob2` to then send a PR. So here's a short summary of the two commits:

1. `StatModel()` now returns a valid empty model (threw an error before)
```r
> StatModel()
Object of class "StatModel"
The type is "fitError"
There number of elements is 0 
```
2. A column of `StatModel`s in a `DataFrame` now displays as expected (threw an error before) 
```r
> df
DataFrame with 2 rows and 2 columns
          x          mods
  <integer>        <list>
1         1 StatModel:rlm
2         2  StatModel:lm
```
3. Update the man page.
4. Added a unit test.

Please discuss any additional updates that need to be done and/or close this issue if you are happy.

**Comment by statOmics** [comment]
Seems excellent to me!
