### ISSUE TITLE
first draft of msqrob2 package  working on simple example

### ISSUE THREAD

**Issue by statOmics** [statOmics/msqrob2#6]
@lgatto @ococrook @ndmeulem First draft of msqrob2 package is functional and can be installed via BiocManager::install("statomics/msqrob2")

Works on simple 3 by 3 cptac.Rmd example. 

Please comment on structure.

@ndmeulem Please evaluate on more complex examples and compare with respect to how many proteins that we loose.

**Comment by ococrook** [comment]
I assume msqrob.R is the main function?

I'll fork locally and to see if it works for me. I'll then send a pull request later making some edits.

**Comment by statOmics** [comment]
@ococrook Yes. In the vignette folder you can find a markdown with an example

**Comment by ococrook** [comment]
Great, thanks!

I get stuck at line 150, which package is combineFeatures exported from?

**Comment by lgatto** [comment]
`combineFeatures` come from `MSnbase`, but is to be replaced by [`Features::aggregateFeatures`](https://github.com/lgatto/Features/blob/master/R/Features-aggregation.R#L76-L79).

**Comment by lgatto** [comment]
I will be evaluating the model class structure asap. I think there is some scope for simplification, but haven't been able to check in details so far.

**Comment by statOmics** [comment]
I feel so to. I implemented it as such based on the discussion at the developers day to have a StatModel object for every protein. I however would prefer the StatModel Object to be an object with the models of all proteins. It could be a list or a DataFrame with a slot params for all models or parameters, a slot for the type of each model, a slot for all posterior variances and a slot for the posterior degrees of freedom. I guess that we would be able to have a row in the rowData the is a DataFrame itself, right?

**Comment by statOmics** [comment]
Laurent,

Does that mean that I have an old Features package because mine does not have the aggregateFeatures function...

Lieven

**Comment by ococrook** [comment]
@statOmics I think you must have an old version. I re-installed fresh and it works for me.

check that everyone works locally for you by devtools::install() in the package directory. Then require(msqrob2).

Let me know if you can't compile the .rmd file

There are bunch of Errors/Warnings to fix - I should get around to them over the weekend

**Comment by statOmics** [comment]
I had already updated it in the mean time and everything works...
